version: '3.7'

services:
  #    brawlhalla_web:
  #        image: php:7.4-apache
  #        container_name: brawlhalla_web
  #        build:
  #            context: .
  #            dockerfile: Dockerfile
  #        env_file:
  #            - .env
  #        ports:
  #            - "8082:8000"
  
  brawlhalla_db:
    image: mariadb:10.5
    container_name: brawlhalla_db
    restart: unless-stopped
    ports:
      - 3303:3306
    environment:
      MYSQL_DATABASE: brawlhalla
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Vladivostok
    volumes:
      - ./dbdata:/var/lib/mysql

volumes:
  mysql_data:
