version: '3.7'

services:
    brawlhalla_web:
        image: php:7.4-apache
        container_name: brawlhalla_web
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8082:8000"

    mysql:
        image: mysql:5.7
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3303:3306"
        environment:
            MYSQL_DATABASE: brawlhalla
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
volumes:
    mysql_data:
